### ISSUE TITLE
Question about sign recording

### ISSUE THREAD

**Issue by Thotsuya** [gabguerin/Sign-Language-Recognition--MediaPipe-DTW#15]
What are the ideal conditions to record videos for a given sign? Light, Background, camera resolution. I have recorded like 30 or so videos for a single sign. But every time I hit r to record, always throws Unknown Sign.

Also note that the camera I'm using has a 1920x1080 resolution at 30fps

**Comment by gabguerin** [comment]
You don't need a perfect set up for the code to perform. A laptop webcam is sufficient.
The only requirement is the location of the videos, they have to be in the folder `data/videos/sign_name/`
